project:
  type: book
  output-dir: _book
  
book:
  title: "Analysing the effect of bog ditches on Sphagnum communities"
  author: "Anders Kolstad"
  repo-url: https://github.com/NINAnor/NINA-ebook-template
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - ch_data_exploration.qmd
    - ch_causal_model.qmd
  appendices:
    - appendix-notes.qmd
    
format:
  html: 
    theme: 
    - cosmo
    - NINAstyle.scss
    code-fold: true
    code-link: true

bibliography: references.bib
csl: NINArefStyle.csl

execute:
  warning: false
  message: false
